### ISSUE TITLE
建议添加调光的设备类型

### ISSUE THREAD

**Issue by liubiqu** [Rokid/rokid-homebase-docs#3]
我们的开关体系都是标准的三个类型：
- '照明开关','light'
- '调光开关','dimmer'
- '窗帘开关','curtain'

**Comment by maxbbn** [comment]
light curtain 我们都有， dimmer 直接用 light 类型就可以了

**Comment by maxbbn** [comment]
添加一个 actions: { brightness: ['up', 'down'] }, 就支持调光
